package app.resolvekit.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.google.devtools.ksp.validate

/**
 * KSP symbol processor that generates [AnyResolveKitFunction] adapters for
 * every class annotated with [@ResolveKit][app.resolvekit.authoring.ResolveKit].
 *
 * For a class `Foo` annotated with @ResolveKit, the processor emits:
 *   - `FooResolveKitAdapter` object in the same package
 *   - Implements `AnyResolveKitFunction` with schema derived from constructor params
 *   - Dispatches to `Foo(...).perform()` with type-coerced arguments
 */
class ResolveKitProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    private val schemaGen = SchemaGenerator()

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver
            .getSymbolsWithAnnotation("app.resolvekit.authoring.ResolveKit")
            .filterIsInstance<KSClassDeclaration>()

        val deferred = mutableListOf<KSAnnotated>()

        symbols.forEach { cls ->
            if (!cls.validate()) {
                deferred.add(cls)
                return@forEach
            }
            try {
                generateAdapter(cls)
            } catch (e: Exception) {
                logger.error("ResolveKitProcessor failed for ${cls.simpleName.asString()}: ${e.message}", cls)
            }
        }

        return deferred
    }

    private fun generateAdapter(cls: KSClassDeclaration) {
        val annotation = cls.annotations.first { it.shortName.asString() == "ResolveKit" }
        val args = annotation.arguments.associate { it.name?.asString() to it.value }

        val name = args["name"] as? String ?: cls.simpleName.asString()
        val description = args["description"] as? String ?: ""
        val timeout = (args["timeout"] as? Int) ?: -1
        val requiresApproval = (args["requiresApproval"] as? Boolean) ?: true

        val packageName = cls.packageName.asString()
        val className = cls.simpleName.asString()
        val adapterName = "${className}ResolveKitAdapter"

        val params = cls.primaryConstructor?.parameters ?: emptyList()
        val schema = schemaGen.generateSchema(params)

        val constructorArgs = params.joinToString(",\n") { param ->
            val paramName = param.name?.asString() ?: return@joinToString ""
            val resolvedType = param.type.resolve()
            val typeName = resolvedType.declaration.simpleName.asString()
            val isNullable = resolvedType.isMarkedNullable
            val coercion = if (isNullable) {
                schemaGen.coercionCallNullable(typeName, paramName)
            } else {
                schemaGen.coercionCall(typeName, paramName)
            }
            "            $paramName = $coercion"
        }

        val timeoutLine = if (timeout == -1) "null" else "$timeout"

        val resultConversion = """when (val r = instance.perform()) {
            is String -> JSONValue.String(r)
            is Boolean -> JSONValue.Bool(r)
            is Int -> JSONValue.Number(r.toDouble())
            is Long -> JSONValue.Number(r.toDouble())
            is Double -> JSONValue.Number(r)
            is Float -> JSONValue.Number(r.toDouble())
            null -> JSONValue.Null
            else -> JSONValue.String(r.toString())
        }"""

        val fileContent = """// Generated by ResolveKit KSP Processor — do not edit manually
package $packageName

import app.resolvekit.core.AnyResolveKitFunction
import app.resolvekit.core.JSONObject
import app.resolvekit.core.JSONValue
import app.resolvekit.core.ResolveKitFunctionContext
import app.resolvekit.core.TypeResolver

object $adapterName : AnyResolveKitFunction {
    override val resolveKitName: String = "$name"
    override val resolveKitDescription: String = "$description"
    override val resolveKitTimeoutSeconds: Int? = $timeoutLine
    override val resolveKitRequiresApproval: Boolean = $requiresApproval
    override val resolveKitParametersSchema: JSONObject = $schema

    override suspend fun invoke(arguments: JSONObject, context: ResolveKitFunctionContext): JSONValue {
        val instance = $className(
$constructorArgs
        )
        return $resultConversion
    }
}
"""
        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(false, cls.containingFile!!),
            packageName = packageName,
            fileName = adapterName
        )
        file.writer().use { it.write(fileContent) }
    }
}
